name: CI

permissions:
  contents: read
  actions: read
  checks: write
  packages: write # Necessary to push to GHCR

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:

  build-container:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Necessary to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} #
      - name: Set lowercase repo name as environment variable
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LC=$REPO_LC" >> $GITHUB_ENV
      - name: Build image with Buildah
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: spinal-image
          tags: latest
          containerfiles: ./dockers/Dockerfile.spinalhdl
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
      - name: Push to GitHub Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io/${{ env.REPO_LC }}

  test:
    runs-on: ubuntu-latest
    needs: build-container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} #

      - name: Make tests
        run: |
          rm -rf .podman/target/test-reports/
          ls -al
          PULL_IMAGE=1 ./dockers/run-spinal-image.sh sbt --no-colors test

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure() # Always run this step
        with:
          name: SBT Tests
          path: .podman/target/test-reports/*.xml # Path to the generated XML reports
          reporter: java-junit
